server:
  port: 8766
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
      #defaultZone: http://localhost:8761/eureka/